version: '3.9'

services:

  dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "35729:35729"

    depends_on:
      - db
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    env_file:
      - ./mise/env/base.env
    environment:
      RAILS_ENV: development

  db:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - db_data/:/root/db/
    env_file:
      - ./mise/env/base.env

  chrome:
    image: selenium/standalone-chrome-debug
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "4444:4444"

  roro:
    image: handsomefencer/roro:latest
    container_name: artifact
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD:/artifact

volumes:
  db_data:
  gem_cache:
  node_modules:
